# values.yaml
global:
  ingressEnabled: true
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - argocd.example.com # Substitua pelo seu domínio ou endereço IP
    tls:
      - secretName: argocd-tls
        hosts:
          - argocd.example.com # Substitua pelo seu domínio ou endereço IP
